bug 6782:  somehow in my testing I missed this exception when creating the event for USER_DELETE.  The change is to get the userAccount by 'idIncludingRemoved' just like getting the account.  The proper userAccount object is returned and the event is successfully created.

status 6782: resolved fixed

